import React from 'react'
import Head from 'next/head'
import Header from './header'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Typography from '@material-ui/core/Typography'
import Button from '@material-ui/core/Button'
import { Link } from '@material-ui/core'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>DiAXS 応募ページ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <main className={styles.main}>
        <Image src="/Diaxs.png" width={ 600 } height={350 } />
        <br></br>
        <p className={styles.description}>
          会社概要
        </p>

        <Typography style={{ color: "#7f7f7f" } }>
          会社概要会社概要会社概要会社概要会社概要会社概要会社概要</Typography>
        <div className={styles.grid}>
          <Link href="/recruit"
            className={styles.card}>Go Recruit</Link>
          <h1
            className={styles.card}>応募する
          </h1>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' kiyomaro in tha house'}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
