import React from 'react'
import Head from 'next/head'
import Header from './header'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Typography from '@material-ui/core/Typography'
import Button from '@material-ui/core/Button'
import Grid from '@material-ui/core/Grid'
import { Link } from '@material-ui/core'
import Paper from '@material-ui/core/Paper'
import { createMuiTheme } from '@material-ui/core/styles'
import { makeStyles } from '@material-ui/core/styles';
import { ThemeProvider } from '@material-ui/styles'

export default function recruit() {
  const useStyles = makeStyles((theme) => ({
  root: {
    flexGrow: 1,
  },
  paper: {
    padding: theme.spacing(3),
    textAlign: 'center',
    color: theme.palette.text.secondary,
  },
  }));
  const theme = createMuiTheme({
    palette: {
      primary: {
        main: '#1e1022'
      },
      secondary: {
        main: '#DF0869'
      }},
  })
  theme.typography.h3 = {
  fontSize: '1.2rem',
  '@media (min-width:800px)': {
    fontSize: '2rem',
  },
  [theme.breakpoints.up('md')]: {
    fontSize: '2.4rem',
  },
  }
  theme.typography.h6 = {
    fontSize: '1.0rem',
  '@media (min-width:800px)': {
    fontSize: '1.2rem',
  },
  [theme.breakpoints.up('md')]: {
    fontSize: '1.5rem',
  },
  }
  const classes = useStyles();
  return (
    <div className={styles.container}>
      <Head>
        <title>DiAXS 応募ページ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ThemeProvider theme={theme}>

      <Header />
      <main className={styles.main}>
        <div className={classes.root}>
          <Grid container spacing={3}>
            <Grid item xs={12}>
              <Paper className={classes.paper} elevation= { 3 }>
                <br></br>
                <Typography variant="h3" style={{color:"#000"}} className={styles.title}>
                  日本のe-sportsを世界へ！！
                </Typography>
                <Typography variant="h6" className={styles.description}>
                  DiAXS社で共に世界で活躍する<br></br>VTuber&プロゲーマー大募集！
                </Typography>
                <br></br>
              </Paper>
            </Grid>
            <Grid item xs={12} style={{textAlign: "center"}}>
              <Button variant="contained" color={'secondary'} onClick={() => console.log("g")}>
                応募する
              </Button>
            </Grid>
            <Grid item xs={12} sm={6}>
              <Paper className={classes.paper} elevation= { 3 }>
                <Typography variant="h4" style={{ color: "#000" }} className={styles.title}>
                  ストリーマー
                </Typography>
                <Typography variant="subtitle2" className={styles.title}>
                  ゲームで稼ぎたくて、ゲームが大好きな方。<br></br><br></br>年齢性別不問！
                </Typography>
              </Paper>
            </Grid>
            <Grid item xs={12} sm={6}>
                <Paper className={classes.paper} elevation={3} >
                <Typography variant="h4" style={{ color: "#000" }} className={styles.title}>
                  大会メンバー
                </Typography>
                <Typography variant="subtitle2" className={styles.title}>
                  17歳〜26歳でゲームで稼ぎたくて<br></br>本気でゲームと向えるスキルのある方。<br></br>性別不問！
                </Typography>
              </Paper>
            </Grid>
            <Grid item xs={6} sm={3}>
              <Paper className={classes.paper} elevation= { 3 }>xs=6 sm=3</Paper>
            </Grid>
            <Grid item xs={6} sm={3}>
              <Paper className={classes.paper} elevation= { 3 }>xs=6 sm=3</Paper>
            </Grid>
            <Grid item xs={6} sm={3}>
              <Paper className={classes.paper} elevation= { 3 }>xs=6 sm=3</Paper>
            </Grid>
            <Grid item xs={6} sm={3}>
              <Paper className={classes.paper} elevation= { 3 }>xs=6 sm=3</Paper>
            </Grid>
          </Grid>
    </div>
          <br></br>
        <Typography variant="h5" style={{ color: "#7f7f7f" } }>
          応募条件</Typography>



        <div className={styles.grid}>
        <Link href="/" className={styles.card}>back to Home</Link>
          <h1
            className={styles.card}
            >応募する
          </h1>
        <Image src="/Diaxs.png" width={400} height={200} />
        </div>
        </main>
        </ThemeProvider>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{''}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
